// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz35aL7J9V-ESNcp82MB8FqKGtYeN9A5s',
    appId: '1:32701014005:web:2853d44e8204ae625acabc',
    messagingSenderId: '32701014005',
    projectId: 'crud-d0a5f',
    authDomain: 'crud-d0a5f.firebaseapp.com',
    storageBucket: 'crud-d0a5f.appspot.com',
    measurementId: 'G-KWTVR410M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV6BoCKubB_abiB5CS3FmwF_6BtdREQvE',
    appId: '1:32701014005:android:cdecffa80e915ac55acabc',
    messagingSenderId: '32701014005',
    projectId: 'crud-d0a5f',
    storageBucket: 'crud-d0a5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpbSdMvZtBjEiqbLI_ChTEtgCpuZxG9sg',
    appId: '1:32701014005:ios:428645d1a2b6938a5acabc',
    messagingSenderId: '32701014005',
    projectId: 'crud-d0a5f',
    storageBucket: 'crud-d0a5f.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpbSdMvZtBjEiqbLI_ChTEtgCpuZxG9sg',
    appId: '1:32701014005:ios:11eac89bc73a78a75acabc',
    messagingSenderId: '32701014005',
    projectId: 'crud-d0a5f',
    storageBucket: 'crud-d0a5f.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
